name: build docker image & push

on:
  push:
    branches:
      - 'master'

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ prabhat295 }}
          password: ${{ dckr_pat_8yb4uuPMrXXiyD0DbATmBLAntro }}
      -
        name: Build and push
        uses: docker/bake-action@v4
        with:
          context: DockerFileFolder/   or .
          push: true
          tags: prabhat295/github:argoimage
